### ISSUE TITLE
Permissions denied for the mounted directories

### ISSUE THREAD

**Issue by dan-m-1** [EccoB/ToPDFConverter#1]
<img width="373" alt="Screenshot 2021-01-10 133346" src="https://user-images.githubusercontent.com/77147601/104122948-7cb63a00-5348-11eb-99ec-6f0574ab24c7.png">

After starting the container with the mounted directories /input and /ouput the container reads the files, but then there is a Permissions denied error for writing the pdfs into the /output directory

**Comment by EccoB** [comment]
Hello,
The ocr runs as a normal user inside the container due to security reasons.
- You can either set your output mount-point access to write others permissions, or run the container as the corresponding user. Or
- Run the container as the user, the input and output folder belongs to with docker run --user XXXX:XXXX

I'll update the README
